# Generated by Django 5.2.7 on 2025-10-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_detail',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='member_detail',
            name='role',
        ),
    ]
