# Generated by Django 5.2.7 on 2025-10-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_member_detail_competition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='lead_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
