# Generated by Django 5.2.7 on 2025-10-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_team_lead_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='lead_postal_code',
            field=models.IntegerField(default=201005, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member_detail',
            name='Postal_code',
            field=models.IntegerField(default='201005', max_length=6),
            preserve_default=False,
        ),
    ]
