# Generated by Django 5.2.7 on 2025-11-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_team_lead_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_detail',
            name='Postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='lead_postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
